# Generated by Django 4.2 on 2023-08-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ein', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
